# app/config/services.yml

services:
    app.request_listener:
        class: AppBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request method="onKernelRequest"}